theme: minima
title: "Erkam Sarı"
author: "Erkam Sarı"
description: "Adnan Menderes University"
permalink: /:title/
date_format: "%d %B, %Y"

# Layout
show_social: true

# Menu
navigation: 
  - {title: "Ana Sayfa ve Duyurular", icon: home}
  - {title: "Dersler"}
  - {title: "CV & Contact"}
external: 
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?user=r44aYPwAAAAJ&hl=tr"}
  - {title: Research Gate, icon: researchgate, url: "https://www.researchgate.net/profile/Erkam-Sari-2"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/ErkamSar2"}
  
  
  
